In [34]:
import pandas as pd
from datetime import datetime

In [41]:
# 1. SELECT() - used for choosing specific columns
selected_data = data[['Year', 'Price', 'Fuel_Type', 'Mileage']]
print("Selected Columns:\n", selected_data.head())

Selected Columns:
    Year  Price Fuel_Type  Mileage
0  2015  12.50    Diesel    19.67
1  2011   4.50    Petrol    13.00
2  2012   6.00    Diesel    20.77
3  2013  17.74    Diesel    15.20
4  2013   3.50    Diesel    23.08

In [46]:
# 2. FILTER () - used for filtering rows where the 'Price' is greater than a certain amount
filtered_data = data[data['Price'] > 10000]
print("\nFiltered Data (Price > 10000):\n", filtered_data.head())

Filtered Data (Price > 10000):
 Empty DataFrame
Columns: [Name, Location, Year, Kilometers_Driven, Fuel_Type, Transmission, Owner_Type, Mileage, Engine, Power, Seats, New_Price, Price, Car_Age]
Index: []

In [48]:
# 3. RENAME() - used for renaming columns name's
renamed_data = data.rename(columns={'Year': 'Manufacture_Year', 'Price': 'Car_Price'})
print("\nRenamed Columns:\n", )
renamed_data.head()

Renamed Columns:

,Name,Location,Manufacture_Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Car_Price,Car_Age
0,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,4.78,12.50,9
1,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13.00,1199.0,88.70,5.0,8.61,4.50,13
2,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,4.78,6.00,12
3,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,4.78,17.74,11
4,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08,1461.0,63.10,5.0,4.78,3.50,11

In [51]:
# 4. MUTATE() - used for creating a new column (like Car_Age from Year)
current_year = datetime.now().year
mutated_data = data.copy()
mutated_data['Car_Age'] = current_year - mutated_data['Year']
print("\nData with 'Car_Age' column:\n", )
mutated_data.head()

Data with 'Car_Age' column:

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age
0,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,4.78,12.50,9
1,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13.00,1199.0,88.70,5.0,8.61,4.50,13
2,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,4.78,6.00,12
3,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,4.78,17.74,11
4,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08,1461.0,63.10,5.0,4.78,3.50,11

In [52]:
# 5. ARRANGE() - used for sorting by 'Price' in descending order
arranged_data = data.sort_values(by='Price', ascending=False)
print("\nData arranged by 'Price' (descending):\n", )
arranged_data.head()

Data arranged by 'Price' (descending):

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age
3952,Land Rover Range Rover 3.0 Diesel LWB Vogue,Hyderabad,2017,25000,Diesel,Automatic,First,13.33,2993.0,255.0,5.0,2.30,160.00,7
5620,Lamborghini Gallardo Coupe,Delhi,2011,6500,Petrol,Automatic,Third,6.40,5204.0,560.0,2.0,4.78,120.00,13
5752,Jaguar F Type 5.0 V8 S,Hyderabad,2015,8000,Petrol,Automatic,First,12.50,5000.0,488.1,2.0,4.78,100.00,9
1457,Land Rover Range Rover Sport SE,Kochi,2019,26013,Diesel,Automatic,First,12.65,2993.0,255.0,5.0,1.39,97.07,5
1917,BMW 7 Series 740Li,Coimbatore,2018,28060,Petrol,Automatic,First,12.05,2979.0,320.0,5.0,4.78,93.67,6

In [54]:
# 6. SUMMARIZE with GROUP BY - Grouping by 'Fuel_Type' and summarizing average 'Price' and 'Mileage'
summary_data = data.groupby('Fuel_Type').agg(
    Avg_Price=('Price', 'mean'),
    Avg_Mileage=('Mileage', 'mean')
).reset_index()
print("\nSummary of Average Price and Mileage by Fuel Type:\n", )
summary_data.head()

Summary of Average Price and Mileage by Fuel Type:

  Fuel_Type  Avg_Price  Avg_Mileage
0    Diesel  12.960686    18.652661
1  Electric  12.875000    18.900000
2    Petrol   5.756688    17.576509